### ISSUE TITLE
Code change for windows

### ISSUE THREAD

**Issue by Aviator75** [nst0022/GroundTraffic#1]
Hi,

I've managed to compile for windows.

What I have done in Makefile.Win :
- change XPSDK213 to XPSDK302
- change the quotation mark in (`"$(CC) $(CFLAGS) /Zs /Z7 /w /showIncludes $< 2>nul: | findstr Note:"`) to ('"$(CC) $(CFLAGS) /Zs /Z7 /w /showIncludes $< 2>nul: | findstr Note:"')

Hope it helps.

**Comment by nst0022** [comment]
I am not happy with your 2nd change, but I can only speak for Linux. 

In Linux, the content of back-ticks "`" is passed to the shell for execution, though I do not understand the additional double-quotes in that line, which could be make-specific.

Are you sure the back-ticks caused a compilation error?

**Comment by Aviator75** [comment]
Hi,

The back-ticks was the only error that make it impossible to compîle in
windows.

Original is : `" =  ` + "
What works : '" = ' + "

I'm not an expert at all, so you should do as you think it's better.

**Comment by nst0022** [comment]
OK, as I am not an expert either, I will leave it as is :-).
