### ISSUE TITLE
Plugin crash on exit

### ISSUE THREAD

**Issue by Aviator75** [nst0022/GroundTraffic#2]
I think there is a problem in groundtraffic.c

Instead of
    /*start line 1098*/
    for(route=airport->routes; route; route=route->next)
    {
        XPLMUnloadObject(route->object.objref);
        route->object.objref=0;
    }
   /* Unregister per-route DataRefs */
    for(i=0; i<dataref_count; i++)
    {
        XPLMDestroyInstance(route->instance_ref); // nst0022
        XPLMUnregisterDataAccessor(ref_datarefs[i]);
        ref_datarefs[i] = 0;
    }
 
You should write 
    /*start line 1098*/
    for(route=airport->routes; route; route=route->next)
    {
        XPLMUnloadObject(route->object.objref);
        route->object.objref=0;
        XPLMDestroyInstance(route->instance_ref); // nst0022
    }
    /* Unregister per-route DataRefs */
    for(i=0; i<dataref_count; i++)
    {
        XPLMUnregisterDataAccessor(ref_datarefs[i]);
        ref_datarefs[i] = 0;
    }

I'm not sure at all, but it doesn't crash with that code.

**Comment by nst0022** [comment]
Yes, your are right, this is one of my dreaded cut&paste errors.
I have fixed this in the upcoming version 1.61
